version: "3"
services:
  backend:
    build: .
    container_name: crud-nest
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db
  
  db:
    image: "mysql:5.6"
    restart: always
    container_name: crud-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=domsgit
      - MYSQL_DATABASE=nestcrud
    volumes:
      - ./db/mysql/data:/var/lib/mysql 
      - ./db/mysql/example_db:/var/example_db 
      - ./db/mysql/conf.d:/etc/mysql/conf.d  
  